### ISSUE TITLE
Inconsistent hold on certain maps

### ISSUE THREAD

**Issue by IsoiKim** [segabl/pd2-useful-bots#20]
So recently, the bots wouldn't always stay in one place as they were told on the tiny stairs in the middle of "The Diamond - Holdout" and at the doors of "Boat Load - Holdout". I can't find a correlation why, but it hasn't happened to me on any other levels yet. I have got footage of it on Boat Load below. I doubt it's due to the doors, as the spot on The Diamond doesn't have a moving object.

### Video: https://youtu.be/VfCrosPnyis

**Comment by segabl** [comment]
looks like something is making them switch cover points, not sure this is holdout specific. you see them walking back to their intended spots though so the objective itself is not broken

**Comment by segabl** [comment]
This seems to be related to them reloading, iirc the attack logic tries to make them move to cover while reloading. you should see it much more form bots with low mag sizes and much less from bots with large ones. If you can confirm this is related I can look into disabling that check.

**Comment by segabl** [comment]
Yeah I'm expecting it to happen less out in the open, as there are usually no defined cover spots close enough.
This is definitely caused by cover searching behavior though so I'll look into that when I have time. As they will return to their original positions relatively quickly, it's not a high priority atm.
